name: CI for Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Run tests
      run: python tests.py
